// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkTluAwGoEpbMN6Y1N3KD9pbXzz92zCpk',
    appId: '1:878424589610:web:ef7406f6a8893fcc9cca53',
    messagingSenderId: '878424589610',
    projectId: 'nexuly',
    authDomain: 'nexuly.firebaseapp.com',
    storageBucket: 'nexuly.firebasestorage.app',
    measurementId: 'G-149H8F237L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2A6Z_z3KVFJ-tJKGO1nqed_cMCVnGcvc',
    appId: '1:878424589610:android:f38b2dadfbb340d69cca53',
    messagingSenderId: '878424589610',
    projectId: 'nexuly',
    storageBucket: 'nexuly.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-D8527DsInUOzpUF5EFbRpjSaBJI9ChA',
    appId: '1:878424589610:ios:1e089a58a0124d929cca53',
    messagingSenderId: '878424589610',
    projectId: 'nexuly',
    storageBucket: 'nexuly.firebasestorage.app',
    iosBundleId: 'com.example.nexulyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-D8527DsInUOzpUF5EFbRpjSaBJI9ChA',
    appId: '1:878424589610:ios:1e089a58a0124d929cca53',
    messagingSenderId: '878424589610',
    projectId: 'nexuly',
    storageBucket: 'nexuly.firebasestorage.app',
    iosBundleId: 'com.example.nexulyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkTluAwGoEpbMN6Y1N3KD9pbXzz92zCpk',
    appId: '1:878424589610:web:32efe29a21fad8729cca53',
    messagingSenderId: '878424589610',
    projectId: 'nexuly',
    authDomain: 'nexuly.firebaseapp.com',
    storageBucket: 'nexuly.firebasestorage.app',
    measurementId: 'G-BX0QYQCYWF',
  );
}
